'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const F=require('./engine');require('./rolling').installPhysics(F);
const baselineDead=F.World.prototype.isDeadBall;
const install=require('./bot-control');install(F);const P=install.playability,{World,Brain,C}=F;
const results=[];function test(name,fn){try{const metrics=fn();results.push({name,pass:true,metrics});console.log('PASS',name,metrics||'');}catch(e){results.push({name,pass:false,error:e.stack});console.error('FAIL',name,e.stack);}}
function step(w,seconds,fn){for(let i=0;i<Math.round(seconds/C.fixedDt);i++){fn?.(i);w.step();w.events=[];}}
function stationary(x=.6,y=.34){const w=new World();w.rules=false;for(const r of w.rods)r.theta=r.targetTheta=Math.PI/2;Object.assign(w.ball,{x,y,z:C.radius,vx:0,vy:0,vz:0,wx:0,wy:0,wz:0});return w;}
test('Two short same-handle taps neutralize once, including mouse',()=>{for(const type of ['touch','mouse','pen']){const d=new P.DoubleTap();d.down(1,5,10,20,0,type);assert.equal(d.up(1,10,20,80),null);d.down(2,5,10,20,160,type);assert.equal(d.up(2,10,20,225),5);d.down(3,5,10,20,260,type);assert.equal(d.up(3,10,20,300),null);}});
test('Dragging, holding, cancelling and different handles do not become double taps',()=>{for(const action of ['drag','hold','cancel','other','late']){const d=new P.DoubleTap();d.down(1,5,10,20,0);d.up(1,10,20,80);d.down(2,action==='other'?3:5,10,20,action==='late'?700:140);if(action==='drag')d.move(2,30,20);assert.equal(d.up(2,10,20,action==='hold'?450:action==='late'?740:200,action==='cancel'),null,action);}});
test('Simultaneous touches on two rods never look like a double tap',()=>{const d=new P.DoubleTap();d.down(1,5,0,0,0);d.down(2,3,0,0,20);d.up(1,0,0,70);d.up(2,0,0,90);d.down(3,3,0,0,150);assert.equal(d.up(3,0,0,220),null);});
test('Neutral releases a pin and cancels pending whip without centering the rod or rewriting the ball',()=>{const w=new World(),r=w.rods[5];r.y=.037;r.targetY=.05;r.theta=4;r.pinIntent=true;r.pinJoint={x:.87};r.driveUntil=r.releaseAt=r.feedUntil=5;r.strikeTarget=8;r.motorFeed=100;const ball=JSON.stringify(w.ball);P.neutral(F,w,r);assert.equal(r.targetY,.037);assert.ok(Math.abs(F.wrap(r.targetTheta+.3))<1e-10);assert.ok(!r.pinJoint&&!r.pinIntent);assert.equal(r.strikeTarget,null);assert.equal(r.driveUntil,-1);assert.equal(JSON.stringify(w.ball),ball);});
test('Normal and rolled-over angles return by a bounded shortest stroke at both ends',()=>{for(const team of [0,1])for(const turn of [-13,-4,1.3,9,19]){const w=stationary(),r=w.rods.find(r=>r.team===team&&r.role==='ATT');r.theta=r.targetTheta=turn;r.y=r.targetY=.026;P.neutral(F,w,r);assert.ok(Math.abs(r.targetTheta-turn)<=Math.PI);step(w,.6);assert.ok(Math.abs(F.wrap(r.theta+.3*r.dir))<.001);assert.ok(Math.abs(r.y-.026)<.00001);}});
test('Explicit pin is required: a slow backward touch cannot silently latch',()=>{const w=new World(),r=w.rods[5];r.directGrip=true;Object.assign(w.ball,{x:r.x+.052,y:.34,z:C.radius,vx:0,vy:0});r.theta=r.targetTheta=.99;const c={depth:0,nz:-1,ny:0,nx:0};w.latchPin(r,c);assert.equal(r.pinJoint,null);w.setPin(r,true);w.latchPin(r,c);assert.ok(r.pinJoint);});
test('Unreachable numerical chatter starts recovery despite resetting the old speed timer',()=>{const w=stationary();let notified=0,reset=0;const d=new F.DeadBallRecovery(true,3);for(let n=0;n<1100;n++){w.ball.vx=n%2?.026:-.026;w.ball.wy=w.ball.vx/C.radius;w.step();const event=d.update(w);if(event==='notice')notified++;if(event==='reserve')reset++;}assert.ok(w.deadTime<=C.fixedDt);assert.equal(notified,1);assert.equal(reset,1);assert.ok(w.isDeadBall());return {noticed:notified,restarts:reset,seconds:w.time};});
test('Reachable human balls, real pins, moving balls and ready time never count as dead',()=>{for(const kind of ['reachable','pin','moving','ready','goal']){const w=stationary(kind==='reachable'?.57:.6);step(w,2);if(kind==='pin')w.rods[3].pinJoint={x:w.ball.x};if(kind==='moving')w.ball.vx=.1;if(kind==='ready')w.serveRemaining=1;if(kind==='goal')w.goalLock=1;assert.equal(w.isDeadBall(),false,kind);}});
test('Paused countdown freezes; a free ball cancels it; disabled auto-reset stays manual',()=>{const w=stationary();step(w,1.4);const d=new F.DeadBallRecovery();assert.equal(d.update(w),'notice');step(w,.5,()=>d.update(w));d.update(w);const t=d.remaining;w.paused=true;step(w,4,()=>d.update(w));assert.equal(d.remaining,t);w.paused=false;w.ball.x=.57;d.update(w);assert.equal(d.visible,false);w.ball.x=.6;step(w,1.4);d.setAuto(false,w);d.update(w);step(w,5,()=>assert.notEqual(d.update(w),'reserve'));assert.ok(d.visible);});
test('Easy and Medium have slower vision, finite hand changes and lower defensive speed than Hard',()=>{assert.ok(F.LEVELS[0].delay>F.LEVELS[1].delay&&F.LEVELS[1].delay>F.LEVELS[2].delay);assert.ok(P.SETTINGS[0].transfer>P.SETTINGS[1].transfer&&P.SETTINGS[1].transfer>P.SETTINGS[2].transfer);assert.ok(P.SETTINGS[0].defend<P.SETTINGS[1].defend&&P.SETTINGS[1].defend<P.SETTINGS[2].defend);return {mediumVisualDelay:F.LEVELS[1].delay,mediumHandTransfer:P.SETTINGS[1].transfer,mediumDefense_m_s:P.SETTINGS[1].defend};});
test('All five Medium profiles choose only straight drives or basic stick passes',()=>{const counts={};for(const name of F.PROFILES.map(p=>p.id)){const w=new World(),b=new Brain(1,1,13,name),r=w.rods[4];const tally={};for(let i=0;i<100;i++){const move=b.pick(w,r,{...w.ball,x:r.x-.04,y:.3,vx:0,vy:0});assert.ok(['Straight drive','Stick pass'].includes(move));tally[move]=(tally[move]||0)+1;}counts[name]=tally;}assert.ok(counts.maya['Stick pass']>counts.bob['Stick pass']);return counts;});
test('Medium waits for an observation instead of reacting to a future sample',()=>{const w=new World(),b=new Brain(1,1);w.time=1;b.history=[{t:1,x:.5,y:.3,vx:0,vy:0}];assert.equal(b.perceived(w,F.LEVELS[1]),null);w.time=1.39;assert.ok(b.perceived(w,F.LEVELS[1]));});
test('Medium cannot instantly take control of a newly selected row',()=>{const w=new World(),b=new Brain(1,1);w.reset(1);step(w,1,()=>b.update(w,C.fixedDt));const hands=b.__hands;assert.ok(hands?.length&&hands.length<=2);for(const h of hands)assert.ok(Number.isFinite(h.ready));return {handChanges:b.memory.handleSwitches};});
test('Rescue covers every bot row and both ends without modifying ball or opponents in update',()=>{const cases=[];for(const team of [0,1])for(const role of ['GK','DEF','MID','ATT'])for(const side of [-1,1]){const w=stationary(),brain=new Brain(team,1,44,'maya'),r=w.rods.find(r=>r.team===team&&r.role===role);for(const a of w.rods){a.theta=a.targetTheta=Math.PI/2;a.motor=a===r;}r.theta=r.targetTheta=-.3*r.dir;r.y=r.targetY=brain.aimY(r,.34);const startX=r.x+side*.069;Object.assign(w.ball,{x:startX,y:.34});let moved=false;for(let i=0;i<240*12;i++){const ball=JSON.stringify(w.ball),enemy=JSON.stringify(w.rods.filter(a=>a.team!==team));brain.update(w,C.fixedDt);assert.equal(JSON.stringify(w.ball),ball);assert.equal(JSON.stringify(w.rods.filter(a=>a.team!==team)),enemy);w.step();w.events=[];if(Math.hypot(w.ball.x-startX,w.ball.y-.34)>.036){moved=true;break;}if(w.botStall)break;}assert.ok(moved||w.botStall,`${team} ${role} ${side}`);cases.push({team,role,side,moved,timeout:!!w.botStall,seconds:w.time});}return {cases};});
test('An intentionally immobilized bot gets an announced timeout rather than endless retries',()=>{const w=stationary(),brain=new Brain(1,1),r=w.rods[2];w.ball.x=r.x-.05;let flagged=false;for(let i=0;i<240*12;i++){brain.update(w,C.fixedDt);for(const a of w.rods)if(a.team===1){a.targetY=a.y;a.targetTheta=a.theta;a.vy=a.omega=0;}w.step();w.events=[];if(w.botStall){flagged=true;assert.equal(w.botStall.reason,'bot-timeout');assert.ok(brain.memory.unstickAttempts>=2);break;}}assert.ok(flagged);return {seconds:w.time,attempts:brain.memory.unstickAttempts};});
test('A human-controlled or human-pinned ball cannot trigger a bot timeout',()=>{for(const kind of ['own','pin']){const w=stationary(kind==='own'?.575:.425),brain=new Brain(1,1);if(kind==='pin'){w.rods[2].controlled=true;}for(let i=0;i<240*12;i++){brain.update(w,C.fixedDt);w.time+=C.fixedDt;}assert.equal(w.botStall,null);}});
const passed=results.filter(r=>r.pass).length;fs.writeFileSync('v10-test-results.json',JSON.stringify({passed,total:results.length,results},null,2));console.log(`${passed}/${results.length} v10 checks`);process.exitCode=passed===results.length?0:1;
