'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto').webcrypto;
const F=require('./engine');require('./rolling').installPhysics(F);require('./bot-control')(F);require('./v11').installPhysics(F);
const N=require('./online'),{C,World}=F,results=[];
function test(name,f){try{const metrics=f();results.push({name,passed:true,metrics});console.log('PASS',name,metrics||'');}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.stack);}}
function rail(side,theta,speed=.9){const w=new World();w.rules=false;for(const r of w.rods){r.motor=false;r.theta=Math.PI/2;}const r=w.rods[5];r.motor=true;r.theta=r.targetTheta=theta;r.directGrip=true;r.targetY=side*r.limit;r.y=side*(r.limit-.07);r.slideScale=speed>.28?1:.03;r.vy=side*speed;Object.assign(w.ball,{x:r.x+Math.sin(theta)*.064,y:side<0?C.radius+.0001:C.width-C.radius-.0001,z:C.radius,vx:0,vy:0,vz:0,wx:0,wy:0,wz:0});return {w,r};}
test('Hard side squeeze physically rebounds at both walls and four foot angles',()=>{const cases=[];for(const side of [-1,1])for(const angle of [0,.18,.32,.5]){const {w}=rail(side,angle);const start={...w.ball};let outward=0,dy=0,dx=0;for(let i=0;i<180;i++){w.step();w.events=[];outward=Math.max(outward,-side*w.ball.vy);dy=Math.max(dy,Math.abs(w.ball.y-start.y));dx=Math.max(dx,Math.abs(w.ball.x-start.x));}assert.ok(outward>.2&&outward<1.2);assert.ok(dy>.01&&dy<.08);assert.ok(dx<.035);cases.push({side,angle,peakOutward:outward,travel_mm:dy*1000});}return cases;});
test('Gentle side pressure does not trigger the hard-squeeze grip yield',()=>{for(const side of [-1,1]){const {w,r}=rail(side,0,.06);r.y=side*(r.limit-.016);r.targetY=r.y;for(let i=0;i<240;i++)w.step();assert.equal(w.stats.railReleases||0,0);}});
test('Passive grip drift removes energy and keeps rotation controllable',()=>{const w=new World(),r=w.rods[5];r.y=0;r.vy=-.4;r.targetY=.1;r.theta=0;r.targetTheta=.3;w.__railYields=new Map([[5,{until:1,side:1}]]);w.moveRods(C.fixedDt);assert.ok(Math.abs(r.vy)<.4&&r.vy<0);assert.ok(r.y<0&&r.theta>0);});
test('A deliberate pull away cancels compliance immediately',()=>{const w=new World(),r=w.rods[5];r.y=.1;r.vy=-.4;r.targetY=0;w.__railYields=new Map([[5,{until:1,side:1}]]);w.moveRods(C.fixedDt);assert.equal(w.__railYields.size,0);});
test('Pin intent cancels passive side yield',()=>{const w=new World(),r=w.rods[5];r.pinIntent=true;w.__railYields=new Map([[5,{until:1,side:1}]]);w.moveRods(C.fixedDt);assert.equal(w.__railYields.size,0);});
test('Predictive bot worlds with a rod subset do not crash on stale yield IDs',()=>{const w=new World();w.__railYields=new Map([[7,{until:1,side:1}]]);w.rods=w.rods.slice(0,2);w.moveRods(C.fixedDt);assert.equal(w.__railYields.size,0);});
test('Reset discards side-contact memory and yielded grips',()=>{const {w}=rail(-1,0);for(let i=0;i<80;i++)w.step();w.reset();assert.equal(w.__railImpact,null);assert.equal(w.__railYields.size,0);});
test('A resting free ball gains no movement from the side-release extension',()=>{const w=new World();w.rules=false;for(const r of w.rods){r.motor=false;r.theta=Math.PI/2;}Object.assign(w.ball,{x:.6,y:.34,z:C.radius,vx:0,vy:0,vz:0,wx:0,wy:0,wz:0});for(let i=0;i<480;i++)w.step();assert.ok(Math.hypot(w.ball.vx,w.ball.vy)<1e-8);assert.equal(w.stats.railReleases||0,0);});
test('Private room codes use crypto randomness and unambiguous 10-character format',()=>{const seen=new Set();for(let i=0;i<200;i++){const code=N.roomCode(crypto);assert.equal(N.parseRoom(code),code);seen.add(code);}assert.equal(seen.size,200);});
test('Invite parsing accepts a code, spaced code or URL and rejects malformed values',()=>{for(const x of ['ABCDEFGH23','abcde fgh23','https://example.com/game/#room=ABCDEFGH23'])assert.equal(N.parseRoom(x),'ABCDEFGH23');for(const x of [null,'<script>','AAAAAAAAA0','123','X'.repeat(1001)])assert.equal(N.parseRoom(x),null);});
test('Mirroring the ball twice recovers position, velocity and equivalent orientation',()=>{const w=new World(),a=N.packBall(w.ball),b=N.mirrorBall(N.mirrorBall(a,C),C);for(let i=0;i<9;i++)assert.ok(Math.abs(a[i]-b[i])<1e-10);const dot=a.slice(9).reduce((s,n,i)=>s+n*b[i+9],0);assert.ok(Math.abs(Math.abs(dot)-1)<1e-6);});
test('The guest-view transformation preserves no-slip rolling direction',()=>{const w=new World(),a=N.packBall(w.ball);a[3]=.4;a[4]=-.2;a[6]=-a[4]/C.radius;a[7]=a[3]/C.radius;const b=N.mirrorBall(a,C);assert.ok(Math.abs(b[6]+b[4]/C.radius)<1e-9);assert.ok(Math.abs(b[7]-b[3]/C.radius)<1e-9);});
test('Quaternion interpolation stays normalized and respects equivalent negative quaternions',()=>{const w=new World(),a=N.packBall(w.ball),b=[...a];for(let i=9;i<13;i++)b[i]*=-1;for(const t of [0,.2,.5,.8,1]){const c=N.interpolateBall(a,b,t);assert.ok(Math.abs(Math.hypot(...c.slice(9))-1)<1e-6);assert.ok(c.every(Number.isFinite));}});
test('A full authoritative snapshot validates and is a small bounded packet',()=>{const w=new World(),p=N.packState(w,1,1,false,false);assert.ok(N.validState(p));assert.ok(JSON.stringify(p).length<2500);return {bytes:JSON.stringify(p).length};});
test('Invalid snapshot arrays and nonfinite values are rejected',()=>{const w=new World();for(const mutate of [p=>p.ball[0]=NaN,p=>p.rods.pop(),p=>p.score[0]=-1,p=>p.serve=99]){const p=N.packState(w,1,1,false,false);mutate(p);assert.ok(!N.validState(p));}});
test('Captured ordinary player controls fit the protocol limits',()=>{const w=new World(),p=N.captureInput(w,1,1,false);assert.ok(N.validInput(p));assert.ok(JSON.stringify(p).length<1200);});
test('Guest intent can affect only Coral rods and cannot mutate the ball or score',()=>{const host=new World(),guest=new World(),g=guest.rods[5];g.targetY=.05;g.targetTheta=-1;g.controlled=true;const own=JSON.stringify(host.rods.filter(r=>r.team===0)),ball=JSON.stringify(host.ball),score=JSON.stringify(host.score);const p=N.captureInput(guest,1,1,false);assert.ok(N.applyInput(host,p,F));assert.equal(host.rods[2].targetY,-.05);assert.equal(host.rods[2].targetTheta,1);assert.equal(JSON.stringify(host.rods.filter(r=>r.team===0)),own);assert.equal(JSON.stringify(host.ball),ball);assert.equal(JSON.stringify(host.score),score);});
test('Malformed input is rejected before any rod is changed',()=>{for(const mutate of [p=>p.rows[0][0]=7,p=>p.rows[0][1]=100,p=>p.rows[0][8]=Infinity,p=>p.rows[0][3]=2,p=>p.rows[3][2]=NaN]){const w=new World(),p=N.captureInput(w,1,1,false);const before=JSON.stringify(w.rods);mutate(p);assert.equal(N.applyInput(w,p,F),false);assert.equal(JSON.stringify(w.rods),before);}});
test('Remote angle differences and lateral targets obey finite motor/travel bounds',()=>{const w=new World(),p=N.captureInput(w,1,1,false);p.rows[0][1]=.24;p.rows[0][2]=10000;assert.ok(N.applyInput(w,p,F));assert.equal(w.rods[7].targetY,-w.rods[7].limit);assert.ok(Math.abs(w.rods[7].targetTheta-w.rods[7].theta)<=4*Math.PI+.0001);});
const passed=results.filter(x=>x.passed).length;fs.writeFileSync('v11-test-results.json',JSON.stringify({passed,total:results.length,results},null,2));console.log(`${passed}/${results.length} v11 checks`);process.exitCode=passed===results.length?0:1;
