'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {World,Brain,DeadBallRecovery,C}=require('./engine');
const R=require('./rolling');const results=[];
function test(name,fn){try{const metrics=fn();results.push({name,pass:true,metrics});console.log('PASS',name,metrics||'');}catch(e){results.push({name,pass:false,error:e.stack});console.log('FAIL',name,e.message);}}
function close(a,b,e=1e-8){assert.ok(Math.abs(a-b)<e,`${a} differs from ${b}`);}
function dead(){const w=new World();for(const r of w.rods){r.theta=r.targetTheta=Math.PI/2;}Object.assign(w.ball,{x:.6,y:.34,z:C.radius,vx:0,vy:0,vz:0,wx:0,wy:0,wz:0});w.deadTime=1.3;return w;}
function step(w,n,cb){for(let i=0;i<n;i++){w.step();cb?.();}}
function obs(w){return {...w.ball,t:w.time,visionTime:w.time,rods:Object.fromEntries(w.rods.map(r=>[r.id,{y:r.y,vy:r.vy,theta:r.theta,omega:r.omega}]))};}
test('Unreachable rest starts a notice once, then a three-second auto-reset request',()=>{const w=dead(),r=new DeadBallRecovery();assert.equal(r.update(w),'notice');assert.ok(r.visible);assert.equal(r.update(w),null);step(w,719,()=>assert.notEqual(r.update(w),'reserve'));w.step();assert.equal(r.update(w),'reserve');assert.equal(r.update(w),null);return {warning_seconds:w.time};});
test('Pause freezes recovery and returning to physical reach cancels it',()=>{const w=dead(),r=new DeadBallRecovery();r.update(w);step(w,120,()=>r.update(w));const before=r.remaining;w.paused=true;step(w,800,()=>r.update(w));close(before,r.remaining);w.paused=false;w.ball.x=.577;r.update(w);assert.equal(r.visible,false);step(w,800,()=>assert.notEqual(r.update(w),'reserve'));});
test('A moving ball, supported pin, goal or ready interval is never auto-reset',()=>{for(const key of ['motion','pin','goal','ready']){const w=dead(),r=new DeadBallRecovery();if(key==='motion')w.ball.vx=.1;if(key==='pin')w.rods[3].pinJoint={x:w.ball.x};if(key==='goal')w.goalLock=1;if(key==='ready')w.serveRemaining=.2;assert.equal(r.update(w),null);assert.equal(r.visible,false);}});
test('Manual-only recovery waits indefinitely and does not modify the physics',()=>{const w=dead(),r=new DeadBallRecovery(false);const before=JSON.stringify(w.ball);r.update(w);w.time+=10;assert.equal(r.update(w),null);assert.ok(r.visible);assert.equal(JSON.stringify(w.ball),before);r.setAuto(true,w);assert.equal(r.remaining,3);});
test('An unreachable ball spinning in place can still be recovered',()=>{const w=dead();w.ball.wz=15;w.deadTime=10;w.step();assert.ok(w.isDeadBall());});
test('All profiles retain learned finishes across rallies, not new matches',()=>{for(const profile of ['bob','maya','theo','iris','kai']){const w=new World(),b=new Brain(1,4,44,profile);b.memory.finishes[2].blocked=3;b.memory.reaims=4;b.history.push(obs(w));b.plans.set(2,{stage:'wind'});w.reset(1);b.beginRally(w);assert.equal(b.memory.finishes[2].blocked,3);assert.equal(b.memory.reaims,4);assert.equal(b.history.length,0);assert.equal(b.plans.size,0);assert.equal(new Brain(1,4,44,profile).memory.finishes[2].blocked,0);}});
test('Observed defender motion invalidates aim without reading future targets',()=>{const w=new World(),b=new Brain(0,4),r=w.rods[5],s=obs(w),p={};p.defense=b.defenseSnapshot(w,r,s);w.rods[6].targetY=.07;w.rods[6].y=.05;assert.equal(b.defenseChanged(w,r,s,p),false);const seen=obs(w);assert.ok(b.defenseChanged(w,r,seen,p));});
test('Reversing defenders receive a bounded, less confident forecast',()=>{const w=new World(),b=new Brain(0,4),e=w.rods[6],o={y:0,vy:.2};const steady=b.forecastShift(e,o,.1);b.memory.defenders[e.id]={samples:30,reversals:14};const irregular=b.forecastShift(e,o,.1);assert.ok(irregular>=0&&irregular<steady);assert.ok(Math.abs(b.forecastShift(e,{vy:100},1))<=.025);return {steady_mm:steady*1000,reversing_mm:irregular*1000};});
test('Scouting obeys its visual delay and saved corners have a bounded preference cost',()=>{const w=new World(),b=new Brain(0,4);w.time=1;w.contactSerial=1;w.touchLog.push({serial:1,t:.99,rod:2,x:.375,y:.34,vx:-2,vy:.1});b.scout(w);assert.equal(b.scoutSerial,0);w.time=1.2;b.scout(w);assert.equal(b.scoutSerial,1);assert.ok(b.threat.some(n=>n>1));const i=b.goalBin(.31);b.memory.finishes[i].blocked=8;const before=b.experienceCost(.31);assert.ok(before>0&&before<.01);b.memory.finishes[i].goals=30;assert.ok(b.experienceCost(.31)<before);});
test('A real scored shot is learned through the live update path before re-serving',()=>{const w=new World(),b=new Brain(0,4,44,'bob');w.reset(0,true);const r=w.rods[5];for(const o of w.rods)if(o!==r){o.theta=o.targetTheta=Math.PI/2;o.motor=false;}for(let i=0;i<2880&&!w.goalLock;i++){b.update(w,C.fixedDt);w.step();w.events=[];}assert.equal(w.score[0],1);b.update(w,C.fixedDt);assert.equal(b.memory.finishes.reduce((n,q)=>n+q.goals,0),1);w.reset(1);b.beginRally(w);assert.equal(b.memory.finishes.reduce((n,q)=>n+q.goals,0),1);});
test('Adaptive strategy never writes ball state or opposing motor targets',()=>{const w=new World(),b=new Brain(0,4);w.reset(0,true);for(let i=0;i<320;i++){const ball=JSON.stringify(w.ball),enemy=JSON.stringify(w.rods.filter(r=>r.team===1));b.update(w,C.fixedDt);assert.equal(JSON.stringify(w.ball),ball);assert.equal(JSON.stringify(w.rods.filter(r=>r.team===1)),enemy);w.step();w.events=[];}});
const views={table:R.camera(),mint:R.camera([1,0,0],[0,-.57,.8216]),coral:R.camera([-1,0,0],[0,.57,.8216]),section:R.camera([1,0,0],[0,0,1])};
test('Ball projection is exactly the table projection, including its vertical shear',()=>{for(const v of [[1,0,0],[0,1,0],[0,0,1],[.3,-.5,.7]]){const p=R.projection(v,views.table);close(p[0],v[0]+.11*v[2]);close(p[1],v[1]-.44*v[2]);}});
for(const [name,view]of Object.entries(views))test(name+': the rolling contact point is stationary in screen space',()=>{for(const [vx,vy]of [[.4,0],[-.4,0],[0,.4],[0,-.4],[.35,-.2]]){const w=[-vy/C.radius,vx/C.radius,0],dt=1e-7,q=R.advance({qw:1},w,dt),before=[0,0,-C.radius],after=R.rotate(before,q);const motion=after.map((n,i)=>n-before[i]+([vx,vy,0][i])*dt);const error=Math.hypot(...R.projection(motion,view))/dt;assert.ok(error<2e-6);}});
for(const [label,vx,vy]of [['forward',.4,0],['backward',-.4,0],['sideways',0,.4],['diagonal',.32,.24]])test(label+': one circumference of no-slip travel makes exactly one rotation',()=>{const w=[-vy/C.radius,vx/C.radius,0],time=2*Math.PI*C.radius/Math.hypot(vx,vy);let q={qw:1};for(let i=0;i<240;i++)q=R.advance(q,w,time/240);const p=R.rotate([.2,.4,.7],q);for(let i=0;i<3;i++)close(p[i],[.2,.4,.7][i]);});
test('Aligning orientation to drift leaves every force and position unchanged',()=>{
 const before=new World(),originalSolve=before.solve,originalIntegrate=before.integrateOrientation;
 before.solve=originalSolve;before.integrateOrientation=originalIntegrate;
 R.installPhysics(require('./engine'));const after=new World();
 for(const w of [before,after]){w.rules=false;for(const r of w.rods){r.theta=r.targetTheta=Math.PI/2;r.motor=false;}Object.assign(w.ball,{x:.46,y:.3,vx:.4,vy:.2,wx:0,wy:0,wz:8});}
 for(let i=0;i<220;i++){before.step();after.step();for(const k of ['x','y','z','vx','vy','vz','wx','wy','wz'])assert.equal(after.ball[k],before.ball[k]);}
});
test('Actual coasting rotation tracks measured ground travel, rather than a timer',()=>{const w=new World();w.rules=false;for(const r of w.rods){r.theta=r.targetTheta=Math.PI/2;r.motor=false;}const vx=.2,vy=.11;Object.assign(w.ball,{x:.44,y:.34,z:C.radius,vx,vy,vz:0,wx:-vy/C.radius,wy:vx/C.radius,wz:0});const axis=[-vy/Math.hypot(vx,vy),vx/Math.hypot(vx,vy),0];let distance=0,angle=0,oldAngle=0;for(let i=0;i<180;i++){const old={...w.ball};w.step();distance+=Math.hypot(w.ball.x-old.x,w.ball.y-old.y);const q=w.ball,a=2*Math.atan2(q.qx*axis[0]+q.qy*axis[1],q.qw),change=2*Math.atan2(Math.sin((a-oldAngle)/2),Math.cos((a-oldAngle)/2));angle+=change;oldAngle=a;}const relative=Math.abs(distance-C.radius*angle)/distance;assert.ok(relative<.0001);return {ground_distance_m:distance,texture_distance_m:C.radius*angle,relative_error:relative};});
test('Skids and backspin are not replaced by a made-up forward rotation',()=>{const unspun=R.advance({qw:1,vx:2},[0,0,0],1);assert.deepEqual(unspun,{qx:0,qy:0,qz:0,qw:1});const p=R.rotate([0,0,1],R.advance({qw:1},[0,-10,0],.01));assert.ok(p[0]<0);});
test('Very fast spin is blurred, not aliased through shortest-arc interpolation',()=>{const slow=R.shutter({wy:10},12),fast=R.shutter({wy:500},12);assert.equal(slow.samples,1);assert.ok(fast.samples>1&&fast.samples<=5&&fast.contrast<.01);const q=R.advance({qw:1},[0,500,0],-.02);close(q.qy,Math.sin(-5));close(q.qw,Math.cos(-5));});
test('Stationary orientation stays identical and quaternion rotation is normalized',()=>{const q=R.advance({qw:1},[2,-3,4],1.7),copy=JSON.stringify(q);for(let i=0;i<100;i++)R.rotate([.4,0,.8],q);assert.equal(JSON.stringify(q),copy);close(Math.hypot(q.qx,q.qy,q.qz,q.qw),1);});
test('Sphere geometry remains a soccer ball with 12 pentagons and 20 hexagons',()=>{assert.equal(R.faces.length,32);assert.equal(R.faces.filter(f=>f.dark).length,12);});
test('Back-rail recovery physically frees both keepers without rewriting the ball',()=>{
 const F=require('./engine');require('./bot-control')(F);const cases=[];
 for(const team of [0,1])for(const level of [1,4])for(const y of [.08,.19,.53,.60]){
  const w=new World(),b=new Brain(team,level,818,'bob');w.reset(team,false);w.rules=false;
  const r=w.rods.find(r=>r.team===team&&r.role==='GK');for(const a of w.rods){a.theta=a.targetTheta=Math.PI/2;a.motor=a===r;}
  r.theta=r.targetTheta=-r.dir*.3;const x=team===0?C.radius:C.length-C.radius;r.y=r.targetY=b.aimY(r,y);
  Object.assign(w.ball,{x,y,vx:0,vy:0,vz:0,wx:0,wy:0,wz:0});let freed=false;
  for(let i=0;i<240*10;i++){const ball=JSON.stringify(w.ball);b.update(w,C.fixedDt);assert.equal(JSON.stringify(w.ball),ball);w.step();w.events=[];if((w.ball.x-x)*r.dir>.08){freed=true;break;}}
  assert.ok(freed);cases.push({team,level,y,seconds:w.time,attempts:b.memory.wallReleases||0});
 }
 return {freed:cases.length,total:16,maxSeconds:Math.max(...cases.map(r=>r.seconds))};
});
const passed=results.filter(r=>r.pass).length;fs.writeFileSync('v8-test-results.json',JSON.stringify({passed,total:results.length,results},null,2));console.log(`${passed}/${results.length} new recovery, adaptation and rolling checks`);process.exitCode=passed===results.length?0:1;
