/* Run node v9-tests.cjs. These are regression fixtures, not table calibration. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const F=require('./engine'),R=require('./rolling'),Input=require('./input');
const original=Object.fromEntries(['solve','contact','supportPins','integrateOrientation'].map(k=>[k,F.World.prototype[k]]));
R.installPhysics(F);require('./bot-control')(F);
const {C,World}=F,results=[];
function test(name,fn){try{const metrics=fn();results.push({name,pass:true,metrics});console.log('PASS',name,metrics||'');}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL',name,e.stack);}}
const run=(w,s,fn)=>{for(let n=0;n<Math.round(s/C.fixedDt);n++){fn?.(n);w.step();w.events=[];}};
function fixture(side=1,team=0,offset=.052){const w=new World();w.reset(team,true);w.rules=false;w.walls=[];const r=w.rods.find(r=>r.team===team&&r.role==='ATT');w.rods=[r];r.theta=r.targetTheta=side*1.4;w.ball.x=r.x+side*offset;w.setPin(r,true);run(w,1.3);assert.ok(r.pinJoint);return {w,r};}
function memory(){const values={};return {values,getItem:k=>values[k]??null,setItem:(k,v)=>values[k]=v};}
function distance(a,b){return Math.hypot(b.x-a.x,b.y-a.y);}
function deltaQ(a,b){return [
 b.qw*(-a.qx)+b.qx*a.qw+b.qy*(-a.qz)-b.qz*(-a.qy),
 b.qw*(-a.qy)-b.qx*(-a.qz)+b.qy*a.qw+b.qz*(-a.qx),
 b.qw*(-a.qz)+b.qx*(-a.qy)-b.qy*(-a.qx)+b.qz*a.qw,
 b.qw*a.qw+b.qx*a.qx+b.qy*a.qy+b.qz*a.qz];}
test('Every configurable action starts with a distinct key',()=>{const s=new Input.BindingStore(memory()),keys=Object.values(s.snapshot()).map(i=>i.code);assert.equal(new Set(keys).size,keys.length);assert.ok(keys.length>=30);return {actions:keys.length};});
test('Rebinding and clearing keys survive a saved reload',()=>{const m=memory(),s=new Input.BindingStore(m);assert.ok(s.assign('0.up','KeyT','T').ok);assert.ok(s.assign('0.shoot','KeyY','Y').ok);assert.ok(s.assign('1.down',null).ok);const loaded=new Input.BindingStore(m);assert.equal(loaded.resolve('KeyT').id,'0.up');assert.equal(loaded.resolve('KeyQ'),null);assert.equal(loaded.get('1.down').code,null);});
test('Conflicting keys are rejected without partially changing the map',()=>{const s=new Input.BindingStore(memory()),before=s.snapshot();const r=s.assign('0.up','KeyW');assert.equal(r.ok,false);assert.equal(r.conflict,'1.up');assert.deepEqual(s.snapshot(),before);});
test('Corrupt, duplicate and unknown saved keymaps fail safely to defaults',()=>{const m=memory(),s=new Input.BindingStore(m);s.assign('0.up','KeyT');const data=JSON.parse(m.values[Input.STORAGE]);data.bindings['1.up'].code='KeyT';m.values[Input.STORAGE]=JSON.stringify(data);assert.equal(new Input.BindingStore(m).get('0.up').code,'KeyQ');m.values[Input.STORAGE]='not json';assert.equal(new Input.BindingStore(m).get('0.up').code,'KeyQ');});
test('Denied storage keeps the session usable without claiming persistence',()=>{const s=new Input.BindingStore({getItem(){throw Error('denied');},setItem(){throw Error('denied');}});assert.equal(s.assign('0.up','KeyT').saved,false);assert.equal(s.get('0.up').code,'KeyT');assert.equal(s.reset(),false);assert.equal(s.get('0.up').code,'KeyQ');});
test('Browser navigation and unsupported keys cannot become bindings',()=>{const s=new Input.BindingStore(memory());for(const code of ['Escape','Tab','ControlLeft','MetaRight','F5','Unidentified','BadCode'])assert.equal(s.assign('0.up',code).ok,false);assert.ok(s.assign('0.up','Numpad8').ok);});
test('Physical codes and printed key labels are separate',()=>{const s=new Input.BindingStore(memory());s.assign('0.up','KeyT','A');assert.equal(s.get('0.up').label,'A');assert.equal(s.resolve('KeyT').id,'0.up');assert.equal(Input.eventCode({key:'t',code:''}),'KeyT');});
test('A trapped ball loses residual twist quickly at both ends and pin sides',()=>{const cases=[];for(const team of [0,1])for(const side of [-1,1])for(const omega of [-80,80,160]){const {w,r}=fixture(side,team);w.ball.wz=omega;const start={...w.ball};let elapsed=0;while(Math.abs(w.ball.wz)>.01&&elapsed<.2){w.step();elapsed+=C.fixedDt;}assert.ok(elapsed<.085);assert.ok(r.pinJoint);assert.ok(distance(start,w.ball)<.0001);cases.push({team,side,initial_rad_s:omega,settled_seconds:elapsed});}return {cases};});
test('A settled pin holds an exactly stable visible orientation for two seconds',()=>{for(const side of [-1,1]){const {w}=fixture(side);w.ball.wz=80;run(w,.2);const before={...w.ball};run(w,2);for(const key of ['x','y','qx','qy','qz','qw','wx','wy','wz'])assert.ok(Math.abs(w.ball[key]-before[key])<1e-10,key);}});
test('Walking and reversing a supported pin rotate the surface with net travel',()=>{const cases=[];for(const side of [-1,1]){const {w,r}=fixture(side);let distanceM=0,angle=0,maxMismatch=0;for(let i=0;i<360;i++){r.targetY=.032*Math.sin(i/360*2*Math.PI);const before={...w.ball};w.step();assert.ok(r.pinJoint);const d=deltaQ(before,w.ball),turn=2*Math.atan2(d[0],d[3]),dy=w.ball.y-before.y;distanceM+=Math.abs(dy);angle+=Math.abs(turn);maxMismatch=Math.max(maxMismatch,Math.abs(-turn*C.radius-dy));}assert.ok(distanceM>.05);assert.ok(maxMismatch<.00001);cases.push({side,travel_m:distanceM,texture_travel_m:angle*C.radius,max_step_error_m:maxMismatch});}return {cases};});
test('Soft resting catches settle without waiting for a distant pin latch',()=>{const cases=[];for(const side of [-1,1]){const {w,r}=fixture(side);w.setPin(r,false);r.theta=r.targetTheta=side*.3;r.catchHeld=true;r.directGrip=false;w.ball.x=r.x+side*.047;w.ball.wz=40;run(w,.7);assert.ok(Math.hypot(w.ball.wx,w.ball.wy,w.ball.wz)<.06);assert.ok(!r.pinJoint);cases.push({side,spin_rad_s:Math.hypot(w.ball.wx,w.ball.wy,w.ball.wz)});}return {cases};});
test('Open-field skids, backspin and airborne motion are not damped by the catch fix',()=>{for(const z of [C.radius,.12])for(const spin of [-30,0,45]){const a=new World(),b=new World();Object.assign(a,original);for(const w of [a,b]){w.rules=false;w.rods=[];w.walls=[];Object.assign(w.ball,{x:.5,y:.2,z,vx:.6,vy:.2,vz:0,wx:0,wy:spin,wz:12});}for(let i=0;i<65;i++){a.step();b.step();for(const key of ['x','y','z','vx','vy','vz','wx','wy','wz'])assert.equal(a.ball[key],b.ball[key],key);}}});
test('Nearby but noncontact balls do not enter a hidden stopping area',()=>{const a=new World(),b=new World();Object.assign(a,original);for(const w of [a,b]){w.rules=false;const r=w.rods[5];w.rods=[r];r.theta=r.targetTheta=0;r.catchHeld=true;Object.assign(w.ball,{x:r.x+.067,y:.34,z:C.radius,vx:.004,vy:0,vz:0,wx:0,wy:.004/C.radius,wz:20});}for(let n=0;n<100;n++){a.step();b.step();for(const k of ['x','y','vx','vy','wx','wy','wz'])assert.equal(a.ball[k],b.ball[k]);}});
test('Pin release keeps its off-axis momentum; a rollover still makes a physical strike',()=>{for(const side of [-1,1]){const {w,r}=fixture(side);w.ball.vx=.04;w.ball.vy=.12;const old={...w.ball};w.setPin(r,false);assert.deepEqual(w.ball,old);}const {w,r}=fixture();w.kick(r,.85,true);run(w,.18);assert.ok(w.stats.shotSpeed>2.5);assert.ok(w.touchLog.some(e=>e.rod===r.id));});
const passed=results.filter(r=>r.pass).length;fs.writeFileSync('v9-test-results.json',JSON.stringify({passed,total:results.length,results},null,2));console.log(`${passed}/${results.length} v9 checks`);process.exitCode=passed===results.length?0:1;
