import {chromium} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4173'],{stdio:'inherit'});
let browser;
try {
  for(let n=0;n<60;n++){try{if((await fetch('http://127.0.0.1:4173/')).ok)break;}catch{}await new Promise(r=>setTimeout(r,500));}
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:980}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4173/app.html?test=1');
  await page.waitForFunction(()=>typeof window.miuTest==='function');
  const checks=await page.evaluate(()=>window.miuTest());
  await mkdir('test-results',{recursive:true});
  await page.locator('#rules').fill('JPG under 240 KB, exactly 600 x 600');
  await page.locator('#apply-rules').click();
  await page.locator('#save-recipe').click();
  await page.locator('#recipe-title').fill('Headshot test');
  await page.locator('#recipe-form button[type=submit]').click();
  if(await page.locator('#recipes option').count()<2)throw Error('Saved rules did not persist');
  checks.push('Rules saved through an actual form, without browser prompt');
  await page.locator('#make').click();
  await page.locator('#quick-save').waitFor({state:'visible'});
  const downloadPromise=page.waitForEvent('download');
  await page.locator('#quick-save').click();
  const downloaded=await downloadPromise;
  const bytes=await readFile(await downloaded.path());
  if(bytes.length>=240000||bytes[0]!==255||bytes[1]!==216)throw Error('Actual UI download was not a JPG below the cap');
  checks.push('Make button and actual JPG download verified');
  await page.screenshot({path:'test-results/workspace.png',animations:'disabled'});
  await page.getByRole('button',{name:'Quick tour'}).click();
  await page.screenshot({path:'test-results/tutorial.png',animations:'disabled'});
  await page.getByRole('button',{name:'I’ll find my way'}).click();
  await page.locator('#image-settings summary').click();
  await page.getByRole('button',{name:'Choose what stays'}).click();
  const box=await page.locator('#edit-canvas').boundingBox();
  await page.mouse.move(box.x+box.width*.2,box.y+box.height*.2);
  await page.mouse.down();
  await page.mouse.move(box.x+box.width*.8,box.y+box.height*.8,{steps:8});
  await page.mouse.up();
  await page.screenshot({path:'test-results/crop.png',animations:'disabled'});
  await page.locator('#edit-apply').click();
  await page.locator('#make').click();
  await page.locator('#quick-save').waitFor({state:'visible'});
  checks.push('Drag crop and subsequent conversion');
  await page.goto('http://127.0.0.1:4173/');
  await page.screenshot({path:'test-results/website.png',fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'test-results/website-mobile.png',fullPage:true,animations:'disabled'});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('Website overflows mobile viewport');
  await page.goto('http://127.0.0.1:4173/app.html?test=1');
  await page.waitForFunction(()=>typeof window.miuTest==='function');
  await page.evaluate(()=>window.miuTest());
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('Workspace overflows mobile viewport');
  await page.screenshot({path:'test-results/workspace-mobile.png',fullPage:true,animations:'disabled'});
  if(errors.length)throw Error(errors.join('\n'));
  await writeFile('test-results/browser.json',JSON.stringify({ok:true,checks,uncaughtErrors:errors},null,2));
} finally {await browser?.close();server.kill();}
