import {PDFDocument,PDFName,PDFDict} from 'pdf-lib';
import * as pdfjs from 'pdfjs-dist';
import workerURL from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import {zipSync,unzipSync} from 'fflate';
import DOMPurify from 'dompurify';
import mammoth from 'mammoth/mammoth.browser';
import {MAX_PIXELS,MAX_ARCHIVE,pageList,outputName,inspectZip,uniqueNames} from './core.js';
pdfjs.GlobalWorkerOptions.workerSrc=workerURL;
export {PDFDocument};
const next=()=>new Promise(r=>setTimeout(r,0));
export function canvas(w,h){w=Math.max(1,Math.round(w));h=Math.max(1,Math.round(h));if(w*h>MAX_PIXELS)throw Error('This picture needs more memory than this editor allows. Use a copy below 32 megapixels.');const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
export function blobCanvas(c,type='image/jpeg',q=.92){return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('The browser could not save this picture.')),type,q));}
export async function image(file){let source=file;const ext=file.name?.split('.').pop().toLowerCase();if(['tif','tiff'].includes(ext)){const mod=await import('utif'),UTIF=mod.default||mod,buf=await file.arrayBuffer(),ifds=UTIF.decode(buf);if(!ifds.length)throw Error('This TIFF has no readable pages.');const p=ifds[0];if((p.t256?.[0]||0)*(p.t257?.[0]||0)>MAX_PIXELS)throw Error('This TIFF is larger than the 32 megapixel limit.');UTIF.decodeImage(buf,p);const c=canvas(p.width,p.height);c.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(UTIF.toRGBA8(p)),p.width,p.height),0,0);return c;}
if(['heic','heif'].includes(ext)){try{return await createImageBitmap(source);}catch{const {default:decode}=await import('heic2any');source=await decode({blob:file,toType:'image/png'});if(Array.isArray(source))source=source[0];}}
try{const bmp=await createImageBitmap(source);if(bmp.width*bmp.height>MAX_PIXELS){bmp.close();throw Error('This image is larger than 32 megapixels.');}return bmp;}catch(e){throw Error(e.message.includes('32 megapixels')?e.message:'This image variant could not be decoded. Try a JPG, PNG or a flattened TIFF copy.');}}
export function edited(source,s){const crop=s.crop||{x:0,y:0,w:1,h:1};let sw=Math.round(source.width*crop.w),sh=Math.round(source.height*crop.h);const rotated=s.rotation%180!==0,c=canvas(rotated?sh:sw,rotated?sw:sh),ctx=c.getContext('2d');ctx.translate(c.width/2,c.height/2);ctx.rotate(s.rotation*Math.PI/180);ctx.scale(s.flip?-1:1,1);ctx.filter=`brightness(${s.brightness}%) contrast(${s.contrast}%) grayscale(${s.grayscale?1:0})`;ctx.drawImage(source,source.width*crop.x,source.height*crop.y,sw,sh,-sw/2,-sh/2,sw,sh);ctx.setTransform(1,0,0,1,0,0);ctx.filter='none';drawMarks(c,s.marks||[]);if(!s.width||!s.height)return c;let w=s.width,h=s.height;if(w<16||h<16||w>10000||h>10000)throw Error('Choose dimensions from 16 to 10,000 pixels.');if(s.dimensionMode==='maximum'){const ratio=Math.min(1,w/c.width,h/c.height);w=Math.round(c.width*ratio);h=Math.round(c.height*ratio);}const out=canvas(w,h),x=out.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,w,h);const scale=s.fit==='cover'?Math.max(w/c.width,h/c.height):Math.min(w/c.width,h/c.height);x.imageSmoothingQuality='high';x.drawImage(c,(w-c.width*scale)/2,(h-c.height*scale)/2,c.width*scale,c.height*scale);return out;}
export function drawMarks(c,marks){const x=c.getContext('2d');for(const m of marks){x.save();x.strokeStyle=m.color||'#db4437';x.fillStyle=m.tool==='hide'?'#000':m.color||'#db4437';x.lineWidth=Math.max(2,c.width*.003);x.lineCap='round';x.lineJoin='round';if(m.tool==='text'){x.font=`${Math.max(14,c.width*.028)}px sans-serif`;x.fillText(m.text,m.x*c.width,m.y*c.height);}else if(m.tool==='pen'){x.beginPath();m.points.forEach((p,i)=>x[i?'lineTo':'moveTo'](p.x*c.width,p.y*c.height));x.stroke();}else{const a=m.x*c.width,b=m.y*c.height,w=m.w*c.width,h=m.h*c.height;if(m.tool==='highlight')x.globalAlpha=.3;if(['hide','highlight'].includes(m.tool))x.fillRect(a,b,w,h);else x.strokeRect(a,b,w,h);}x.restore();}}
export async function pdfOpen(item){if(!item.pdf)item.pdf=await pdfjs.getDocument({data:new Uint8Array(await item.file.arrayBuffer()),isEvalSupported:false,enableXfa:false,useSystemFonts:true}).promise;return item.pdf;}
export async function pdfPage(item,index=0,scale=2){const doc=await pdfOpen(item),p=await doc.getPage(index+1),v=p.getViewport({scale:Math.min(3,scale)});const c=canvas(v.width,v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;return c;}
export async function word(file){inspectZip(new Uint8Array(await file.arrayBuffer()));const result=await mammoth.convertToHtml({arrayBuffer:await file.arrayBuffer()});const html=DOMPurify.sanitize(result.value,{ALLOWED_TAGS:['p','h1','h2','h3','h4','strong','em','u','s','br','ul','ol','li','table','tr','td','th','thead','tbody','a','img','blockquote','sup','sub'],ALLOWED_ATTR:['src','colspan','rowspan'],ALLOW_DATA_ATTR:false});const el=document.createElement('div');el.innerHTML=html;el.querySelectorAll('img').forEach(img=>{if(!/^data:image\/(png|jpeg|gif|webp);base64,/i.test(img.getAttribute('src')||''))img.remove();});return el.innerHTML;}
export async function workbook(file){inspectZip(new Uint8Array(await file.arrayBuffer()));const {default:Excel}=await import('exceljs');const wb=new Excel.Workbook();await wb.xlsx.load(await file.arrayBuffer());return wb;}
export function readZip(bytes){inspectZip(bytes);return unzipSync(bytes);}
export async function makeZip(entries){const total=entries.reduce((n,e)=>n+e.blob.size,0);if(total>MAX_ARCHIVE)throw Error('Choose files totaling less than 120 MB for this ZIP.');const names=uniqueNames(entries.map(e=>e.name)),map={};for(let i=0;i<entries.length;i++){map[names[i]]=[new Uint8Array(await entries[i].blob.arrayBuffer()),{level:entries[i].compress?6:0}];await next();}const data=zipSync(map),opened=unzipSync(data);for(const [name,[bytes]]of Object.entries(map)){if(opened[name]?.length!==bytes.length||!bytes.every((b,i)=>b===opened[name][i]))throw Error('The ZIP verification failed.');}return new Blob([data],{type:'application/zip'});}
export function hasSignature(doc){return doc.context.enumerateIndirectObjects().some(([,o])=>o instanceof PDFDict&&(o.has(PDFName.of('ByteRange'))||String(o.get(PDFName.of('FT')))==='/Sig'));}
function cleanPDF(doc){doc.setTitle('');doc.setAuthor('');doc.setSubject('');doc.setKeywords([]);doc.setProducer('');doc.setCreator('');for(const k of ['CreationDate','ModDate']){const info=doc.context.lookup(doc.context.trailerInfo.Info);if(info instanceof PDFDict)info.delete(PDFName.of(k));}doc.catalog.delete(PDFName.of('Metadata'));}
export async function imagePDF(images){const doc=await PDFDocument.create();for(const c of images){const jpg=await blobCanvas(c,'image/jpeg',.91),im=await doc.embedJpg(await jpg.arrayBuffer());const scale=Math.min(1,540/c.width,720/c.height),page=doc.addPage([c.width*scale,c.height*scale]);page.drawImage(im,{x:0,y:0,width:page.getWidth(),height:page.getHeight()});}cleanPDF(doc);return new Blob([await doc.save()],{type:'application/pdf'});}
async function encodeImage(c,format,quality){if(format==='pdf')return imagePDF([c]);if(format==='tiff'){const mod=await import('utif'),U=mod.default||mod;return new Blob([U.encodeImage(c.getContext('2d').getImageData(0,0,c.width,c.height).data,c.width,c.height)],{type:'image/tiff'});}const type={jpg:'image/jpeg',png:'image/png',webp:'image/webp'}[format];if(!type)throw Error('Choose a supported picture format.');if(format==='jpg'){const bg=canvas(c.width,c.height),x=bg.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(c,0,0);c=bg;}return blobCanvas(c,type,quality);}
export async function processImage(item,signal,progress){const s=item.settings;let c=edited(item.image||await image(item.file),s),out;for(let round=0;round<10;round++){if(signal.aborted)throw Error('Stopped.');out=await encodeImage(c,s.format,.96);if(!s.limit||out.size<s.limit)break;if(['jpg','webp'].includes(s.format)){let lo=.08,hi=.96,best=null;for(let i=0;i<8;i++){if(signal.aborted)throw Error('Stopped.');const q=(lo+hi)/2,b=await encodeImage(c,s.format,q);if(b.size<s.limit){lo=q;best=b;}else hi=q;progress?.(.05+round*.06+i*.01);await next();}if(best){out=best;break;}}
if(s.width&&s.height&&s.dimensionMode==='exact')throw Error('That size limit is too small at these exact dimensions. Increase the limit or choose a smaller size.');const ratio=Math.max(.45,Math.min(.85,Math.sqrt(s.limit/out.size)*.9)),nextC=canvas(Math.max(16,c.width*ratio),Math.max(16,c.height*ratio));nextC.getContext('2d').drawImage(c,0,0,nextC.width,nextC.height);c=nextC;}
if(s.limit&&out.size>=s.limit)throw Error('The file cannot meet this size limit. Choose a larger limit.');if(['jpg','png','webp'].includes(s.format)){const check=await createImageBitmap(out);if(check.width!==c.width||check.height!==c.height)throw Error('The saved picture could not be verified.');check.close();}return{blob:out,name:outputName(item,s.format),note:`${c.width} × ${c.height} pixels · original photo tags not copied`};}
export async function processPDF(item,signal,progress){const s=item.settings,bytes=await item.file.arrayBuffer(),source=await PDFDocument.load(bytes,{updateMetadata:false});if(hasSignature(source)&&!s.signatureOK)throw Error('This PDF contains signature fields. Approve changing signatures before creating a modified copy.');const pages=pageList(s.pages,source.getPageCount());let out;
if(s.flatten){let scale=2;for(let attempt=0;attempt<6;attempt++){const d=await PDFDocument.create();for(let i=0;i<pages.length;i++){if(signal.aborted)throw Error('Stopped.');const c=await pdfPage(item,pages[i],scale);drawMarks(c,(s.marks||[]).filter(m=>m.page===pages[i]));const jpg=await blobCanvas(c,'image/jpeg',Math.max(.38,.88-attempt*.09)),im=await d.embedJpg(await jpg.arrayBuffer()),box=source.getPage(pages[i]).getSize(),p=d.addPage([box.width,box.height]);p.drawImage(im,{x:0,y:0,...box});progress?.((i+1)/pages.length);await next();}cleanPDF(d);out=new Blob([await d.save()],{type:'application/pdf'});if(!s.limit||out.size<s.limit)break;scale*=.78;}}
else{if(s.marks?.length)throw Error('Drawing on a PDF requires approving a picture-only copy.');const doc=await PDFDocument.create();const copied=await doc.copyPages(source,pages);copied.forEach(p=>doc.addPage(p));if(s.clean)cleanPDF(doc);else{doc.setTitle(source.getTitle()||'');doc.setAuthor(source.getAuthor()||'');}out=new Blob([await doc.save()],{type:'application/pdf'});}
if(s.limit&&out.size>=s.limit)throw Error('This PDF is still above the limit. Approve a picture-only copy for stronger reduction, or raise the limit.');const check=await PDFDocument.load(await out.arrayBuffer());if(check.getPageCount()!==pages.length)throw Error('The saved page count did not match.');return{blob:out,name:outputName(item,'pdf'),note:`${pages.length} pages · ${s.flatten?'picture-only: text, forms and links removed':'page content copied; document-level features may change'}`};}
export async function combine(items){const out=await PDFDocument.create();for(const item of items){const blob=item.result?.blob||item.file;if(blob.type==='application/pdf'||item.kind==='pdf'){const doc=await PDFDocument.load(await blob.arrayBuffer());if(hasSignature(doc))throw Error('Combine copies without digital signatures. Combining would change their signature validity.');(await out.copyPages(doc,doc.getPageIndices())).forEach(p=>out.addPage(p));}else if(item.kind==='image'){const c=await image(blob);const im=await out.embedJpg(await (await blobCanvas(c)).arrayBuffer()),sc=Math.min(1,540/c.width,720/c.height),p=out.addPage([c.width*sc,c.height*sc]);p.drawImage(im,{x:0,y:0,width:p.getWidth(),height:p.getHeight()});}else throw Error('Choose only pictures and PDFs to combine.');}cleanPDF(out);return new Blob([await out.save()],{type:'application/pdf'});}
