/* Jelly Jam 2 UI. Host owns the world; guests send inputs and requests only. */
(function(){
'use strict';
const E=JellyEngine,$=id=>document.getElementById(id),modal=$('modal');
const renderer=new JellyRenderer($('game')),preview=new JellyRenderer($('preview'));
let state=E.create(0),mode='local',playing=false,paused=false,soloActive=0,seq=0,lastSeq=-1,world=0,remoteInput={},remoteAt=0,ready=[false,false],away=[false,false],pauseReason='',winShown=false,modalKind='',guestDraw=null,lastStateAt=0,soundOn=false,audio,toastTimer,announceTimer,lastRound=0,mapChapter=0,mapSelected=0,selectedLevel=0,hadConnection=false;
const keys=new Set(),pointers=new Map(),pulses=[{},{}];let remotePulses={};let records={},settings={touch:'auto'};
try{records=JSON.parse(localStorage.getItem('jelly-jam-v2')||'{}')||{};if(typeof records!=='object'||Array.isArray(records))records={};const saved=JSON.parse(localStorage.getItem('jj2-settings')||'{}');if(['auto','on','off'].includes(saved.touch))settings.touch=saved.touch;}catch{}
const online=()=>mode==='host'||mode==='guest';const me=()=>mode==='guest'?1:0;
const time=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
const safeRecord=i=>{const r=records[i];return r&&Number.isFinite(r.time)&&r.time>0&&Number.isFinite(r.deaths)&&r.deaths>=0?r:null;};
const completed=()=>E.levels.filter((_,i)=>safeRecord(i)).length;
const badges=()=>E.chapters.filter((_,c)=>E.levels.slice(c*10,c*10+10).every(l=>safeRecord(l.id))).length;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4000);}
function announce(message){$('announcement').textContent=message;$('announcement').classList.add('show');clearTimeout(announceTimer);announceTimer=setTimeout(()=>$('announcement').classList.remove('show'),2400);}
function clearInputs(){keys.clear();pointers.clear();pulses[0]={};pulses[1]={};remotePulses={};document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));if(mode==='guest')sendInput(true);}
function tone(type){if(!soundOn)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});const notes={jump:[330],super:[390,780],spring:[220,880],star:[740,1100],gate:[440,660],rescue:[200,110],win:[523,659,784,1046],dash:[300,900],portal:[550,220,660],power:[440,880],phase:[620,420],key:[660,880],rotate:[440,550],lever:[330,440],lit:[659,880,1046],rune:[523,659],wrong:[180,140],land:[170]};(notes[type]||[520]).forEach((hz,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.07;o.frequency.setValueAtTime(hz,t);g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(.04,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.15);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.17);});}catch{}}
function closeModal(){if(modal.open)modal.close();modalKind='';modal.dataset.kind='';}
function openModal(kind,html){clearInputs();modalKind=kind;modal.dataset.kind=kind;$('modalContent').innerHTML=html;if(!modal.open)modal.showModal();}
const closeButton='<button class="close" id="closeDialog" aria-label="Close dialog">×</button>';
function dialogClose(){if(modalKind==='win'||modalKind==='disconnect')return;if(modalKind==='lobby'){room.close();mode='local';closeModal();return;}closeModal();if(playing){if(online())showPause();else resumeLocal();}}
modal.addEventListener('cancel',e=>{e.preventDefault();dialogClose();});modal.addEventListener('click',e=>{if(e.target.id==='closeDialog')dialogClose();});
function applyTouch(){const show=settings.touch==='on'||settings.touch==='auto'&&matchMedia('(pointer: coarse)').matches;document.body.dataset.touch=show?'on':'off';$('touchMode').value=settings.touch;$('touchToggle').textContent='Touch: '+settings.touch;try{localStorage.setItem('jj2-settings',JSON.stringify(settings));}catch{}clearInputs();}
$('touchMode').onchange=e=>{settings.touch=e.target.value;applyTouch();};$('touchToggle').onclick=()=>{settings.touch=['auto','on','off'][(['auto','on','off'].indexOf(settings.touch)+1)%3];applyTouch();};matchMedia('(pointer: coarse)').addEventListener?.('change',applyTouch);
function showHome(){room.close();hadConnection=false;playing=false;paused=false;mode='local';clearInputs();closeModal();$('home').hidden=false;$('play').hidden=true;document.body.classList.remove('in-game');$('stageVeil').hidden=true;const url=new URL(location.href);url.hash='';history.replaceState(null,'',url);$('collection').textContent=`${completed()} / ${E.levels.length} team seals · ${badges()} / ${E.chapters.length} badges`;} 
function updateControls(){const who=mode==='guest'?1:mode==='solo'?soloActive:0;document.querySelectorAll('.touch-player').forEach(el=>el.hidden=mode!=='local'&&Number(el.dataset.player)!==who);$('swap').hidden=mode!=='solo';document.body.dataset.mode=mode;
 if(online()){$('peachKeys').innerHTML=`<b class="${who?'mint':'peach'}-text">${who?'◆ You are Mint':'● You are Peach'}</b> A / D / W or arrows · S / ↓ dash · E / Enter use`;$('mintKeys').textContent='Tab away safely. Return and both press Ready.';}
 else if(mode==='solo'){$('peachKeys').innerHTML=`<b class="${who?'mint':'peach'}-text">${who?'Mint':'Peach'} selected</b> A / D / W · S / Shift dash · E use`;$('mintKeys').textContent='Tab switches buddy · the other stays put';}
 else{$('peachKeys').innerHTML='<b class="peach-text">● Peach</b> A / D move · W jump · S dash · E use';$('mintKeys').innerHTML='<b class="mint-text">◆ Mint</b> ← / → move · ↑ jump · ↓ dash · Enter use';}
}
function start(newMode='local',level=selectedLevel){room.close();hadConnection=false;mode=newMode;soloActive=0;away=[false,false];loadLevel(level);showPlay();$('game').focus({preventScroll:true});}
function showPlay(){playing=true;$('home').hidden=true;$('play').hidden=false;document.body.classList.add('in-game');updateControls();updateHUD();if(!online())$('networkStatus').textContent=mode==='solo'?'● Solo practice':'● Local co-op';}
function loadLevel(level){state=E.create(level);world++;lastRound=state.round;guestDraw=null;remoteInput={};ready=[false,false];paused=online()&&(document.hidden||away[1]);pauseReason=paused?'Waiting for both tabs.':'';winShown=false;renderer.particles=[];renderer.camera=null;renderer.overview=null;closeModal();clearInputs();selectedLevel=state.level;updateHUD();sendState();if(paused)showPause();}
function sText(s,r,i){return s.stored[i]?'stored ✓':s.lit[i]?(r.store?'charging '+Math.round(s.lightCharge[i]*100)+'%':'lit'):'dark';}
function updateHUD(){const l=E.levels[state.level];$('levelTag').textContent=l.tag;$('levelTitle').textContent=String(state.level+1).padStart(2,'0')+' / '+l.name;$('starCount').textContent=state.stars.map(b=>b?'★':'☆').join(' ');$('timer').textContent=time(state.t);$('tip').textContent=l.hint;$('attempts').textContent='Attempt '+(state.rescues+1);$('pause').textContent=paused?'Ready / resume':'Ⅱ Pause';$('stageVeil').hidden=!paused;$('powerStatus').textContent=state.players.map((p,i)=>(i?'◆':'●')+' '+(p.dashUnlocked?(p.dashReady?'⚡ ready':'⚡ used'):'no dash')).join(' · ');$('phaseStatus').textContent=[l.switches.length?'Phase '+state.phase:'',...l.receivers.map((r,i)=>r.id+': '+(sText(state,r,i))),l.song.length?'♪ '+l.song.map((n,i)=>(i<state.song?'✓ ':'')+n).join(' → '):''].filter(Boolean).join(' · ');
 $('lessonText').textContent=l.lesson; $('lessonTitle').textContent='How this stage works'; $('overview').hidden=l.width<=1000&&l.height<=600;const ov=renderer.overview===true||(renderer.overview===null&&l.camera==='overview');$('overview').textContent=ov?'↗ Follow':'⊞ Overview';$('overview').setAttribute('aria-pressed',String(ov));
 for(const b of document.querySelectorAll('[data-key="action"]')){b.hidden=!(l.mirrors.length||l.levers.length);const who=Number(b.dataset.p),near=E.interactables(state,who).length>0;b.classList.toggle('charged',near);b.title=near?'Operate nearest mirror or lever':'E / Enter: operate nearby mirrors and levers';}
 
 for(const b of document.querySelectorAll('[data-key="dash"]')){const p=state.players[Number(b.dataset.p)];b.hidden=!l.powerups.length&&!p.dashUnlocked;b.disabled=!p.dashUnlocked;b.classList.toggle('charged',p.dashReady);b.title=p.dashUnlocked?'Dash; landing refills it':'Find a lightning crystal first';}
}
function sendState(){if(mode==='host'&&room.connected)room.send({type:'state',seq:++seq,world,state:E.snapshot(state),paused,ready:[...ready],away:[document.hidden,away[1]],reason:pauseReason});}
function pauseTogether(reason='Taking a breather.'){clearInputs();paused=true;pauseReason=reason;ready=[false,false];remoteInput={};if(mode==='guest')room.send({type:'pause'});sendState();updateHUD();}
function resumeLocal(){paused=false;clearInputs();closeModal();updateHUD();}
function markReady(){clearInputs();if(!online()){resumeLocal();return;}if(!room.connected){room.reconnect();return;}if(document.hidden)return;
 if(mode==='guest'){room.send({type:'ready'});return;}ready[0]=true;maybeResume();}
function maybeResume(){if(mode!=='host')return;if(ready.every(Boolean)&&!document.hidden&&!away.some(Boolean)&&room.connected){paused=false;pauseReason='';remoteInput={};clearInputs();if(modalKind==='pause'||modalKind==='disconnect')closeModal();}else showPause();sendState();updateHUD();}
function showPause(){if(!playing||state.won)return;const isNet=online();const sig=[pauseReason,...ready,...away,room.connected].join('|');if(modalKind==='pause'&&modal.dataset.signature===sig)return;
 openModal('pause',`${closeButton}<div class="eyebrow">${isNet?'YOUR RUN IS SAFE':'TAKE A BREATHER'}</div><h2 id="modalTitle">${isNet?'Back together?':'Paused, not defeated.'}</h2><p id="pauseReason"></p>${isNet?`<div class="ready-grid"><span>● Peach: <b>${away[0]?'tab away':ready[0]?'ready ✓':'waiting'}</b></span><span>◆ Mint: <b>${away[1]?'tab away':ready[1]?'ready ✓':'waiting'}</b></span></div><p>Both players press Ready after returning. The level will not restart.</p>`:''}<button class="primary" id="resume">${isNet?(ready[me()]?'Ready ✓ · waiting for buddy':'I’m ready →'):'Resume →'}</button><button class="secondary" id="pauseRetry">Restart the whole level</button><button class="quiet" id="pauseMap">Level map</button><button class="quiet" id="leave">Return to menu</button>`);modal.dataset.signature=sig;$('pauseReason').textContent=pauseReason||'Your positions and puzzle progress are preserved.';$('resume').onclick=markReady;$('pauseRetry').onclick=retry;$('pauseMap').onclick=()=>chooseLevel();$('leave').onclick=showHome;
}
function retry(){if(mode==='guest'){room.send({type:'restart'});return;}if(online()&&(away.some(Boolean)||document.hidden)){toast('Both buddies need to return first.');return;}loadLevel(state.level);}
function chooseLevel(chapter=playing?Math.floor(state.level/10):mapChapter){if(playing&&!paused)pauseTogether('Choosing a stage.');mapChapter=E.clamp(chapter,0,E.chapters.length-1);mapSelected=mapChapter*10;if(playing&&Math.floor(state.level/10)===mapChapter)mapSelected=state.level;drawMap();}
function drawMap(){const ch=E.chapters[mapChapter],clears=E.levels.slice(mapChapter*10,mapChapter*10+10).filter(l=>safeRecord(l.id)).length;
 const coords=Array.from({length:10},(_,i)=>({x:9+(i<5?i:9-i)*20.5,y:i<5?28:72}));const path=coords.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');
 openModal('map',`${closeButton}<div class="eyebrow">THE PORTAL ATLAS · ${E.levels.length} LEVELS</div><h2 id="modalTitle">Choose your next “aha.”</h2><div class="chapter-tabs" role="tablist" aria-label="Chapters">${E.chapters.map((c,i)=>`<button role="tab" aria-selected="${i===mapChapter}" data-chapter="${i}">${c.icon} ${i+1}. ${c.name}</button>`).join('')}</div><div class="map-heading"><div><b>${ch.icon} ${ch.name}</b><p>${ch.subtitle}</p></div><span>${clears}/10 seals ${clears===10?'✦':''}</span></div><div class="atlas" aria-label="Level path"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="${path}"/></svg>${coords.map((p,j)=>{const i=mapChapter*10+j,l=E.levels[i],r=safeRecord(i);return `<button class="level-node ${r?'cleared':''} ${i===mapSelected?'selected':''}" style="--x:${p.x}%;--y:${p.y}%" data-level="${i}" aria-label="Level ${i+1}: ${l.name}, ${l.difficulty}${r?', completed':''}" aria-pressed="${i===mapSelected}"><strong>${i+1}</strong><span>${r?'✓':l.difficulty==='Expert'?'♛':l.difficulty==='Brain teaser'?'?':'◇'}</span></button>`;}).join('')}</div><div id="levelDetail"></div><div class="map-legend">✓ completed · ? logic puzzle · ♛ expert · all stages open</div><p class="collection-note">${completed()}/${E.levels.length} team seals. Clear each chapter for its badge. Gold = no deaths under par; silver = no deaths; bronze = cleared.</p>`);
 document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{mapChapter=Number(b.dataset.chapter);mapSelected=mapChapter*10;drawMap();});document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{mapSelected=Number(b.dataset.level);document.querySelectorAll('[data-level]').forEach(n=>{n.classList.toggle('selected',n===b);n.setAttribute('aria-pressed',String(n===b));});mapDetail();});mapDetail();
}
function mapDetail(){const l=E.levels[mapSelected],r=safeRecord(mapSelected);$('levelDetail').innerHTML=`<div><span class="difficulty">${l.difficulty}</span><h3>${String(l.id+1).padStart(2,'0')} · ${l.name}</h3><p>${l.hint}</p><small>${r?`Best ${time(r.time)} · ${r.medal} medal`:`Par ${time(l.par)} · not cleared yet`}</small></div><button class="primary" id="playSelected" ${mode==='guest'&&playing?'disabled':''}>${mode==='guest'&&playing?'Host chooses the stage':'Play this level →'}</button>`;$('playSelected').onclick=()=>{selectedLevel=mapSelected;if(playing)loadLevel(mapSelected);else start('local',mapSelected);};}
function showHelp(){if(playing&&!paused)pauseTogether('Reading the field guide.');openModal('help',`${closeButton}<div class="eyebrow">FIELD GUIDE</div><h2 id="modalTitle">Easy controls. Sneaky puzzles.</h2><div class="help-row"><b>Move, jump, and dash.</b>Peach: A / D, W, S. Mint: arrows, ↑, ↓. Online/solo: either layout works; Shift also dashes. Touch controls: Auto / On / Off at the start or in the header.</div><div class="help-row"><b>One team. One life.</b>Either buddy dies → BOTH restart. Stars, keys, crates, and switches reset. No mid-level checkpoints.</div><div class="help-row"><b>Rings, crystals, and flowers.</b>Matching letters link portals. Walk in to warp; jump over to skip. Crystals unlock/refill dash. Land to refill. Walk into crates to push. Crates can hold flowers.</div><div class="help-row"><b>Read the symbols.</b>Filled flower = hold. Hollow flower = leave empty. Split flower = exactly one. Striped dial flips phase. Cracked ledges crumble; dashed red lines are sleeping beams.</div><div class="help-row"><b>Wind, mirrors, and stored light.</b>Fans lift you automatically. E / Enter / ↻ operates nearby mirrors and levers. Golden light is safe. Crates and stone walls block it; thin ledges let it pass. Ringed cells store light once charged.</div><div class="help-row"><b>A tune, not a race.</b>Step onto runes in the displayed order. A wrong note resets only the tune. Completed tunes stay completed until the team dies.</div><div class="help-row"><b>Talk before you move.</b>Each level teaches its rule below the stage. The hint button reveals a nudge first, then the solution. Hard stages need careful timing as well as logic.</div><p>R retries. Escape pauses. Solo: Tab switches buddy. Online: tabbing away pauses the team; both press Ready after returning.</p><button id="gotIt" class="primary">Got it →</button>`);$('gotIt').onclick=dialogClose;}
function showHint(){if(!paused)pauseTogether('Thinking through the puzzle.');const l=E.levels[state.level];openModal('hint',`${closeButton}<div class="eyebrow">A NUDGE, NOT A SPOILER</div><h2 id="modalTitle">${l.name}</h2><p>${l.hint}</p><button class="secondary" id="revealSolution">I’m stuck · reveal the plan</button><p id="solutionText" hidden></p><button class="primary" id="hintBack">Back to the puzzle →</button>`);$('revealSolution').onclick=()=>{$('solutionText').hidden=false;$('solutionText').textContent=l.solution;$('revealSolution').disabled=true;};$('hintBack').onclick=dialogClose;}
function showWin(){winShown=true;const l=E.levels[state.level],r=safeRecord(state.level),medal=state.rescues===0?(state.t<=l.par?'gold':'silver'):'bronze';const rank={bronze:1,silver:2,gold:3};records[state.level]={time:Math.min(state.t,r?.time||Infinity),deaths:Math.min(state.rescues,r?.deaths??Infinity),medal:rank[medal]>rank[r?.medal||'bronze']?medal:r?.medal||medal};try{localStorage.setItem('jelly-jam-v2',JSON.stringify(records));}catch{}
 const final=state.level===E.levels.length-1;openModal('win',`<div class="result-icon">${final?'♛':'✦'}</div><div class="eyebrow">${medal.toUpperCase()} TEAM MEDAL</div><h2 id="modalTitle">${final?'One final brilliant victory.':'Two brains. One victory.'}</h2><p>${final?'You cleared the final stage. Chase the remaining seals and gold medals on the atlas.':'A new seal for your atlas. The next puzzle is waiting.'}</p><div class="result-stats"><div><b>${time(state.t)}</b><span>FINAL ATTEMPT</span></div><div><b>${state.rescues}</b><span>TEAM DEATHS</span></div><div><b>${completed()}/${E.levels.length}</b><span>SEALS</span></div></div><button class="primary" id="nextLevel" ${mode==='guest'?'disabled':''}>${mode==='guest'?'Host chooses what’s next':final?'Return to the atlas':'Next level →'}</button><button class="secondary" id="winMap">Open level map</button><button class="quiet" id="winRetry">Retry for a better medal</button><button class="quiet" id="winMenu">Main menu</button>`);$('nextLevel').onclick=()=>final?chooseLevel():loadLevel(state.level+1);$('winMap').onclick=()=>chooseLevel();$('winRetry').onclick=retry;$('winMenu').onclick=showHome;}
function lobby(){room.close();hadConnection=false;openModal('lobby',`${closeButton}<div class="eyebrow">ONLINE CO-OP</div><h2 id="modalTitle">Bring your favorite brain.</h2><label class="field-label" for="startLevel">Starting level</label><select id="startLevel" class="stage-select">${E.levels.map(l=>`<option value="${l.id}" ${l.id===selectedLevel?'selected':''}>${l.id+1}. ${l.name} · ${l.difficulty}</option>`).join('')}</select><button class="primary" id="hostRoom">Create a room →</button><div class="rule">or join your buddy</div><form id="joinForm" class="room-form"><input id="roomInput" aria-label="Room code" maxlength="12" autocomplete="off" spellcheck="false" placeholder="8-letter code"><button class="primary" type="submit">Join</button></form><p id="roomError" class="error" role="status"></p><p>Free direct browser connection. Strict networks may block it. Tab away safely; don’t close the host’s page.</p>`);$('hostRoom').onclick=()=>{selectedLevel=Number($('startLevel').value);state=E.create(selectedLevel);world++;mode='host';$('hostRoom').disabled=true;room.start('host');};$('joinForm').onsubmit=e=>{e.preventDefault();mode='guest';room.start('guest',$('roomInput').value);};}
function waiting(code){openModal('lobby',`${closeButton}<div class="eyebrow">ROOM READY · LEVEL ${state.level+1}</div><h2 id="modalTitle">Your +1 is invited.</h2><p>Send the invite link or room code. Play begins when your buddy joins.</p><div class="room-code" id="roomCode">${code.slice(0,4)} ${code.slice(4)}</div><button class="primary" id="copyInvite">Copy invite link ↗</button><button class="secondary" id="copyCode">Copy room code</button><p id="roomError" class="error" role="status">Waiting for your buddy…</p>`);$('copyCode').onclick=()=>copy(code);$('copyInvite').onclick=()=>{const url=new URL(location.href);url.search='';url.hash='room='+code;copy(location.protocol==='file:'?code:url.href);};}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copied. Send it to your buddy!');}catch{const el=document.createElement('textarea');el.value=text;$('modalContent').append(el);el.select();let ok=false;try{ok=document.execCommand('copy');}catch{}el.remove();if(!ok&&$('roomError'))$('roomError').textContent=text;toast(ok?'Copied!':'Copy the invite shown in the dialog.');}}
function disconnected(message){paused=true;ready=[false,false];remoteInput={};clearInputs();updateHUD();$('networkStatus').textContent='● Reconnecting…';openModal('disconnect',`<div class="eyebrow">RUN PRESERVED</div><h2 id="modalTitle">Finding your buddy…</h2><p id="disconnectMessage"></p><div class="room-code">${room.code.slice(0,4)} ${room.code.slice(4)}</div><button id="rejoin" class="primary">Reconnect now →</button><button id="continueLocal" class="secondary">Continue locally</button><button id="disconnectHome" class="quiet">Main menu</button>`);$('disconnectMessage').textContent=message;$('rejoin').onclick=()=>room.reconnect();$('continueLocal').onclick=()=>{room.close();mode='local';away=[false,false];resumeLocal();showPlay();};$('disconnectHome').onclick=showHome;}
const room=new JellyNetwork.Room({ready:waiting,status:message=>{if($('roomError'))$('roomError').textContent=message;else $('networkStatus').textContent=message;},error:message=>{if($('roomError')){$('roomError').textContent=message;if($('hostRoom'))$('hostRoom').disabled=false;}else toast(message);},
 connected:(role,rejoined)=>{const returning=rejoined||hadConnection;hadConnection=true;mode=role;lastSeq=-1;lastStateAt=performance.now();guestDraw=null;remoteInput={};remoteAt=performance.now();away=role==='host'?[document.hidden,room.remoteHidden]:[room.remoteHidden,document.hidden];ready=[false,false];paused=returning||away.some(Boolean);pauseReason=returning?'Reconnected. Your level and progress are unchanged.':'Waiting for both tabs.';closeModal();showPlay();$('networkStatus').textContent='● Connected · '+(role==='host'?'Peach':'Mint');if(role==='host'){sendState();if(paused)showPause();}else{paused=true;room.send({type:'resync'});} },
 disconnected,stalled:()=>{if(!paused){paused=true;ready=[false,false];pauseReason='Waiting for a fresh connection. Your run is frozen.';clearInputs();showPause();}},wake:()=>{if(playing&&online()){if(mode==='host'){away[0]=false;sendState();}else room.send({type:'resync'});}},latency:ms=>{if(online()&&room.connected)$('networkStatus').textContent='● '+(mode==='host'?'Peach':'Mint')+' · '+Math.round(ms)+' ms';},
 message:d=>{
  if(mode==='host'){
   if(d.type==='input'&&d.world===world&&d.round===state.round&&d.level===state.level){if(!paused){for(const k of ['jump','dash','action'])if(d[k]===true&&!remoteInput[k])remotePulses[k]=true;}remoteInput=paused?{}:{left:d.left===true,right:d.right===true,jump:d.jump===true,dash:d.dash===true,action:d.action===true};remoteAt=performance.now();}
   else if(d.type==='pause'){pauseTogether('Your buddy paused.');if(!['map','help','hint'].includes(modalKind))showPause();}
   else if(d.type==='presence'){away[1]=d.hidden===true;if(away[1]){pauseTogether('Your buddy stepped away.');if(!['map','help','hint'].includes(modalKind))showPause();}else{sendState();if(paused&&modalKind==='pause')showPause();}}
   else if(d.type==='ready'){away[1]=false;ready[1]=true;maybeResume();}
   else if(d.type==='resync'){remoteInput={};sendState();}
   else if(d.type==='restart'&&!away.some(Boolean)&&!document.hidden)loadLevel(state.level);
  }else if(mode==='guest'&&d.type==='state'&&Number.isSafeInteger(d.seq)&&d.seq>lastSeq&&Number.isSafeInteger(d.world)&&E.validSnapshot(d.state)&&Array.isArray(d.ready)&&d.ready.length===2&&Array.isArray(d.away)&&d.away.length===2){
   lastSeq=d.seq;lastStateAt=performance.now();const previous=state,changed=d.world!==world||previous.round!==d.state.round;world=d.world;state=d.state;paused=d.paused===true;ready=d.ready.map(x=>x===true);away=d.away.map(x=>x===true);pauseReason=typeof d.reason==='string'?d.reason.slice(0,160):'';
   if(changed){winShown=false;guestDraw=null;clearInputs();closeModal();renderer.particles=[];}
   if(paused&&!state.won&&!['map','help','hint'].includes(modalKind))showPause();else if(!paused&&['pause','disconnect'].includes(modalKind))closeModal();
   if(state.stars.filter(Boolean).length>previous.stars.filter(Boolean).length)tone('star');if(state.dead&&!previous.dead)tone('rescue');updateHUD();
  }
 }
});
function keyboardSet(i){return i===0?{left:keys.has('KeyA'),right:keys.has('KeyD'),jump:keys.has('KeyW')||keys.has('Space'),dash:keys.has('KeyS')||keys.has('ShiftLeft'),action:keys.has('KeyE')}:{left:keys.has('ArrowLeft'),right:keys.has('ArrowRight'),jump:keys.has('ArrowUp'),dash:keys.has('ArrowDown')||keys.has('ShiftRight'),action:keys.has('Enter')};}
function inputFor(i){const a=keyboardSet(i);for(const k of ['jump','dash','action'])a[k]=a[k]||pulses[i][k];for(const p of pointers.values())if(p.player===i)a[p.key]=true;return a;}
function currentInputs(){if(paused||modal.open||state.dead||document.hidden)return [{},{}];if(mode==='local')return [inputFor(0),inputFor(1)];const a=inputFor(0),b=inputFor(1),merged={};for(const k of ['left','right','jump','dash','action'])merged[k]=a[k]||b[k];if(mode==='solo'){const list=[{},{}];list[soloActive]=merged;return list;}return mode==='host'?[merged,performance.now()-remoteAt<350?{...remoteInput,jump:remoteInput.jump||remotePulses.jump,dash:remoteInput.dash||remotePulses.dash,action:remoteInput.action||remotePulses.action}:{}]:[{},merged];}
function sendInput(clear=false){if(mode==='guest'&&room.connected){const a=clear?{}:currentInputs()[1];room.send({type:'input',world,round:state.round,level:state.level,left:!!a.left,right:!!a.right,jump:!!a.jump,dash:!!a.dash,action:!!a.action});pulses[0]={};pulses[1]={};}}
function swap(){if(mode!=='solo')return;clearInputs();soloActive=1-soloActive;updateControls();announce(soloActive?'◆ Mint’s turn':'● Peach’s turn');}
const gameCodes=new Set(['KeyA','KeyD','KeyW','KeyS','ShiftLeft','ShiftRight','Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyE','Enter']);
window.addEventListener('keydown',e=>{if(!playing||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='Escape'){e.preventDefault();if(modal.open)dialogClose();else{pauseTogether();showPause();}return;}if(modal.open)return;if(e.code==='Enter'&&e.target.closest?.('button'))return;if(e.code==='KeyR'&&!e.repeat){e.preventDefault();retry();return;}if(e.code==='Tab'&&mode==='solo'){e.preventDefault();if(!e.repeat)swap();return;}if(gameCodes.has(e.code)){e.preventDefault();if(!keys.has(e.code)){const who=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','ShiftRight','Enter'].includes(e.code)?1:0;if(['KeyW','Space','ArrowUp'].includes(e.code))pulses[who].jump=true;if(['KeyS','ShiftLeft','ShiftRight','ArrowDown'].includes(e.code))pulses[who].dash=true;if(['KeyE','Enter'].includes(e.code))pulses[who].action=true;}keys.add(e.code);sendInput();}});
window.addEventListener('keyup',e=>{keys.delete(e.code);if(playing&&gameCodes.has(e.code)){e.preventDefault();sendInput();}});window.addEventListener('blur',clearInputs);
function presence(){clearInputs();if(!playing)return;if(!online()){if(document.hidden){pauseTogether('You stepped away.');showPause();}return;}away[me()]=document.hidden;room.presence(document.hidden);if(document.hidden){pauseTogether('A buddy stepped away.');if(!['map','help','hint'].includes(modalKind))showPause();}else{if(mode==='host')sendState();if(paused&&modalKind==='pause')showPause();}}
document.addEventListener('visibilitychange',presence);window.addEventListener('online',()=>room.wake());window.addEventListener('pagehide',e=>{if(e.persisted){if(playing){pauseTogether('Page suspended.');room.presence(true);}}else room.destroy();});window.addEventListener('pageshow',e=>{if(e.persisted){room.wake();if(playing&&paused&&!document.hidden&&!['map','help','hint','win'].includes(modalKind))showPause();}});
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{if(!playing||paused||modal.open||state.dead)return;e.preventDefault();b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{player:Number(b.dataset.p),key:b.dataset.key});b.classList.add('pressed');if(['jump','dash','action'].includes(b.dataset.key))pulses[Number(b.dataset.p)][b.dataset.key]=true;sendInput();});const release=e=>{pointers.delete(e.pointerId);if(!Array.from(pointers.values()).some(p=>p.player===Number(b.dataset.p)&&p.key===b.dataset.key))b.classList.remove('pressed');sendInput();};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);b.addEventListener('contextmenu',e=>e.preventDefault());}
$('local').onclick=()=>start('local');$('solo').onclick=()=>start('solo');$('online').onclick=lobby;$('adventureMap').onclick=()=>chooseLevel();$('help').onclick=showHelp;$('hint').onclick=showHint;$('brand').onclick=e=>{e.preventDefault();if(playing){pauseTogether();showPause();}else showHome();};$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(soundOn));tone('click');};$('pause').onclick=()=>{if(!paused)pauseTogether();showPause();};$('restart').onclick=retry;$('levels').onclick=()=>chooseLevel();$('swap').onclick=swap;
$('overview').onclick=()=>{const lv=E.levels[state.level];renderer.overview=!(renderer.overview===true||(renderer.overview===null&&lv.camera==='overview'));$('overview').textContent=renderer.overview?'↗ Follow':'⊞ Overview';$('overview').setAttribute('aria-pressed',String(renderer.overview));};$('lessonGuide').onclick=()=>{if(playing&&!paused)pauseTogether('Learning this machine.');const l=E.levels[state.level];openModal('help',`${closeButton}<div class="eyebrow">IN-LEVEL FIELD GUIDE</div><h2 id="modalTitle">${l.name}</h2><div class="help-row"><b>THIS STAGE</b>${l.lesson}</div>${l.guides.map(g=>`<div class="help-row">${g}</div>`).join('')}<p>One death restarts both. Golden light is safe. The Hint button reveals a plan only when you ask.</p><button id="gotIt" class="primary">Let’s try it →</button>`);$('gotIt').onclick=dialogClose;};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('Use landscape orientation for the largest play area.');}catch{toast('Fullscreen is not available here. Try landscape orientation.');}};
let last=performance.now(),acc=0,lastPaint=performance.now(),sendClock=0,hudClock=0;
setInterval(()=>{const now=performance.now(),elapsed=Math.min(.08,(now-last)/1000);last=now;sendClock+=elapsed;hudClock+=elapsed;
 if(playing&&!paused&&!state.won&&mode!=='guest'&&!document.hidden){acc+=elapsed;let steps=0;while(acc>=E.DT&&steps++<5){E.step(state,currentInputs());pulses[0]={};pulses[1]={};remotePulses={};acc-=E.DT;renderer.effects(state);if(state.round!==lastRound){lastRound=state.round;clearInputs();remoteInput={};}
 for(const e of state.events){tone(e.type);if(e.type==='super')announce('SUPER BUDDY BOUNCE!');if(e.type==='power')announce('DASH READY · S / ↓ / lightning button');if(e.type==='key')announce('Key found. A new route is open.');if(e.type==='phase')announce('PHASE '+state.phase);if(e.type==='rune')announce('♪ '+state.song+' / '+E.levels[state.level].song.length);if(e.type==='wrong')announce('Wrong note · tune reset, try again');if(e.type==='lit'&&state.stored.some(Boolean))announce('Sunlight stored · the circuit remembers');}
 if(state.won)break;}}else acc=0;
 if(sendClock>=1/30){sendClock=0;if(mode==='host')sendState();else if(mode==='guest')sendInput();}
 if(playing&&hudClock>.15){hudClock=0;updateHUD();}if(playing&&state.won&&!winShown)showWin();
 if(mode==='guest'&&playing&&room.connected&&!paused&&now-lastStateAt>6000){paused=true;pauseReason='Waiting for the host to return. Your run is frozen.';ready=[false,false];clearInputs();showPause();room.send({type:'resync'});}
},1000/60);
function paint(now){const dt=Math.min(.04,(now-lastPaint)/1000);lastPaint=now;if(playing){let draw=state;if(mode==='guest'){if(!guestDraw)guestDraw=state.players.map(p=>({...p}));for(let i=0;i<2;i++){const q=state.players[i],p=guestDraw[i],snap=state.dead||Math.abs(p.x-q.x)>100||Math.abs(p.y-q.y)>100,a=snap?1:1-Math.exp(-dt*25),x=p.x+(q.x-p.x)*a,y=p.y+(q.y-p.y)*a;Object.assign(p,q,{x,y});}draw={...state,players:guestDraw};}renderer.draw(draw,now/1000,dt);}else preview.draw(E.create(10),now/1000,dt,true);requestAnimationFrame(paint);}requestAnimationFrame(paint);
Object.defineProperty(window,'JellyJam',{value:{get state(){return E.snapshot(state);},get mode(){return mode;},get paused(){return paused;},get connected(){return room.connected;},get roomCode(){return room.code;},get remoteInput(){return {...remoteInput};},get ready(){return [...ready];},get away(){return [...away];},get world(){return world;},get touchMode(){return settings.touch;}}});
applyTouch();if(matchMedia('(max-height:560px) and (orientation:landscape)').matches)$('lessonPanel').open=false;$('collection').textContent=`${completed()} / ${E.levels.length} team seals · ${badges()} / ${E.chapters.length} badges`;const code=new URLSearchParams(location.hash.slice(1)).get('room');if(code){lobby();$('roomInput').value=JellyNetwork.cleanCode(code);$('roomError').textContent='You’re invited. Press Join to connect.';}
})();
