const{spawn}=require('node:child_process'),fs=require('node:fs/promises'),path=require('node:path');
const ffmpeg=require('ffmpeg-static'),ffprobe=require('@ffprobe-installer/ffprobe').path;
let running=null;const allowedFormats='mov,matroska,webm,avi,mp3,wav,flac,aac,ogg,aiff,mpeg,mpegts';
function exec(binary,args,timeout=1200000){return new Promise((resolve,reject)=>{const p=spawn(binary,args,{windowsHide:true,stdio:['ignore','pipe','pipe']});running=p;let out='',err='',ended=false;const timer=setTimeout(()=>{p.kill('SIGKILL');},timeout);p.stdout.on('data',d=>out=(out+d).slice(-2000000));p.stderr.on('data',d=>err=(err+d).slice(-12000));p.on('error',fail);p.on('close',code=>{if(ended)return;ended=true;clearTimeout(timer);if(running===p)running=null;if(code!==0)reject(Error(err.includes('Invalid data')?'This media file could not be decoded.':'Media processing stopped or this codec is unsupported. '+err.slice(-450)));else resolve(out);});function fail(e){if(ended)return;ended=true;clearTimeout(timer);if(running===p)running=null;reject(e);}});}
const cancel=()=>{running?.kill('SIGKILL');};
async function probe(file){return JSON.parse(await exec(ffprobe,['-v','error','-protocol_whitelist','file,pipe','-format_whitelist',allowedFormats,'-show_streams','-show_format','-of','json',file],60000));}
function number(v,low,high,fallback){const n=Number(v);if(!Number.isFinite(n))return fallback;return Math.max(low,Math.min(high,n));}
async function convert(input,s,dir){const info=await probe(input),video=info.streams.find(v=>v.codec_type==='video'),audio=info.streams.find(v=>v.codec_type==='audio'),format=['mp4','webm','mp3','wav','m4a'].includes(s.format)?s.format:'mp4',isVideo=['mp4','webm'].includes(format),duration=Number(info.format.duration||video?.duration||audio?.duration);if(!Number.isFinite(duration)||duration<=0)throw Error('The length of this media file could not be read.');if(isVideo&&!video)throw Error('This file does not contain a video track.');if(!isVideo&&!audio)throw Error('This file does not contain a sound track.');if(!isVideo&&s.mute)throw Error('A sound-only export cannot also have Remove sound selected.');const start=number(s.start,0,duration,0),end=s.end?number(s.end,0,duration,duration):duration;if(end<=start+.02)throw Error('The end must come after the start.');const speed=number(s.speed,.25,4,1),length=(end-start)/speed,limit=number(s.limit,0,2000000000,0),output=path.join(dir,'converted.'+format);let bits=limit?Math.floor(limit*8/length*.87):0;const audioBits=audio&&!s.mute?isVideo?Math.min(128000,Math.max(24000,Math.floor(bits*.15)||128000)):Math.min(192000,Math.max(16000,bits||192000)):0;if(bits&&bits-audioBits<18000&&isVideo)throw Error('This size limit is too small for the clip length. Trim more or increase the limit.');
const vf=[];if(isVideo){if(s.crop){const c=s.crop,x=number(c.x,0,.99,0),y=number(c.y,0,.99,0),w=number(c.w,.01,1-x,1-x),h=number(c.h,.01,1-y,1-y);vf.push(`crop=trunc(iw*${w}/2)*2:trunc(ih*${h}/2)*2:trunc(iw*${x}/2)*2:trunc(ih*${y}/2)*2`);}const rotation=number(s.rotation,0,270,0);if(rotation===90)vf.push('transpose=1');if(rotation===180)vf.push('hflip,vflip');if(rotation===270)vf.push('transpose=2');if(s.flip)vf.push('hflip');if(s.width&&s.height){const w=Math.round(number(s.width,16,10000,1920)),h=Math.round(number(s.height,16,10000,1080));if(w%2||h%2)throw Error('Choose even width and height numbers for video, such as 1080 × 1080.');if(s.fit==='cover')vf.push(`scale=${w}:${h}:force_original_aspect_ratio=increase,crop=${w}:${h}`);else vf.push(`scale=${w}:${h}:force_original_aspect_ratio=decrease,pad=${w}:${h}:(ow-iw)/2:(oh-ih)/2:color=white`);}else vf.push('scale=trunc(iw/2)*2:trunc(ih/2)*2');const bright=(number(s.brightness,50,150,100)-100)/100,contrast=number(s.contrast,50,150,100)/100;if(bright||contrast!==1||s.grayscale)vf.push(`eq=brightness=${bright}:contrast=${contrast}:saturation=${s.grayscale?0:1}`);vf.push(`setpts=(PTS-STARTPTS)/${speed}`);}
let remaining=speed;const af=[];while(remaining>2){af.push('atempo=2');remaining/=2;}while(remaining<.5){af.push('atempo=0.5');remaining/=.5;}af.push(`atempo=${remaining}`, 'asetpts=PTS-STARTPTS');
for(let attempt=0;attempt<4;attempt++){const args=['-nostdin','-hide_banner','-y','-v','error','-protocol_whitelist','file,pipe','-format_whitelist',allowedFormats,'-ss',String(start),'-t',String(end-start),'-i',input,'-map_metadata','-1','-map_chapters','-1'];if(isVideo){args.push('-map','0:v:0','-vf',vf.join(','),'-c:v',format==='webm'?'libvpx-vp9':'libx264','-pix_fmt','yuv420p');if(format==='mp4')args.push('-preset','fast','-movflags','+faststart');if(bits)args.push('-b:v',String(Math.floor(bits-audioBits)),'-maxrate',String(Math.floor((bits-audioBits)*1.2)),'-bufsize',String(Math.floor(bits*2)));else args.push('-crf',format==='mp4'?'23':'32');}else args.push('-vn');if(audio&&!s.mute){args.push('-map','0:a:0','-af',af.join(','),'-c:a',format==='wav'?'pcm_s16le':format==='mp3'?'libmp3lame':format==='webm'?'libopus':'aac');if(format!=='wav')args.push('-b:a',String(audioBits));}else args.push('-an');args.push(output);await exec(ffmpeg,args);const st=await fs.stat(output);if(!limit||st.size<limit)break;if(attempt===3||format==='wav')throw Error('The converted media is still above the limit. Trim it more or increase the limit.');bits=Math.floor(bits*limit/st.size*.86);if(isVideo&&bits-audioBits<18000)throw Error('The limit is too small for this clip length.');}
const check=await probe(output),actual=Number(check.format.duration);if(!Number.isFinite(actual)||Math.abs(actual-length)>Math.max(.7,length*.06))throw Error('The saved clip length did not pass verification.');const bytes=await fs.readFile(output);if(limit&&bytes.length>=limit)throw Error('The saved clip exceeds the size limit.');return{bytes,mime:{mp4:'video/mp4',webm:'video/webm',mp3:'audio/mpeg',wav:'audio/wav',m4a:'audio/mp4'}[format],note:`${actual.toFixed(1)} seconds · ${speed}× speed · ${isVideo?format==='mp4'?'H.264 / AAC':'VP9 / Opus':'sound export'} · source tags not copied`};}
async function selfTest(dir){const source=path.join(dir,'sample.mp4');await exec(ffmpeg,['-nostdin','-y','-v','error','-f','lavfi','-i','testsrc=size=320x240:rate=15','-f','lavfi','-i','sine=frequency=440:sample_rate=44100','-t','2','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac',source]);const result=await convert(source,{format:'mp4',speed:2,brightness:100,contrast:100},dir);if(result.bytes.length<1000)throw Error('Native video conversion failed');return result.note;}
module.exports={convert,cancel,selfTest};
